name: medico-sam
channels:
    - conda-forge
dependencies:
    - micro_sam
    # Note: installing the pytorch package from conda-forge will generally
    # give you the most optimized version for your system, if you have a modern
    # enough OS and CUDA version (CUDA >= 12). For older versions, you can
    # specify the CUDA version by pinning libtorch.
    # For example, add this line for a CUDA 11 version:
    # - libtorch=*=cuda11*
    # or, to enforce a CPU installation, change to
    # - "pytorch=*=cpu*"
    - pytorch >=2.5
    - zarr <3
    - pip
    - pip:
        - https://github.com/anwai98/tukra.git
